apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: abphoif3i-go 
  janus-idp.io/tekton: abphoif3i-go
  backstage.io/kubernetes-id: abphoif3i-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: abphoif3i-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml